import { ReactNode } from 'react'
import './globals.css'
import { Poppins, Fira_Code } from 'next/font/google'
import Provider from '@/components/Provider'

const poppies = Poppins({
  variable: '--font-poppies',
  subsets: ['latin'],
  weight: ['400', '600', '700', '800'],
})
const fira = Fira_Code({
  variable: '--font-fira-code',
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata = {
  title: 'upskill.code',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
  openGraph: {
    images: '/ogimage.png',
  },
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${poppies.variable} ${fira.variable}`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
